# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4680e5dee17ac5ff2c0d2ea8c288ab7255564faeaa962405adb9bf349629a86dac4295460a0d6919586c8ca20952d126df97a148835fee9981d5f1541125e2

test:
  secret_key_base: 0b4192d95f7a7d38a605bd826bb161e67ffb06997699a6b3bdfe70096cd34b45f7822f847af0e8eff1ab76531ce1aa3c5151a1bc1875a123a5c53c74f07ba94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
